name: lhp
version: 0.0.4
github: vst/lhp
license: MIT
author: Vehbi Sinan Tunalioglu
maintainer: vst@vsthost.com
copyright: Copyright (c) 2024 Vehbi Sinan Tunalioglu
extra-source-files:
  - README.md
  - CHANGELOG.md
description: Please see the README on GitHub at <https://github.com/vst/lhp#readme>
dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  ghc-options:
    - '-Wall'
    - '-Werror'
    - '-Wunused-packages'
  dependencies:
    - aeson
    - aeson-combinators
    - autodocodec
    - autodocodec-schema
    - bytestring
    - file-embed
    - monad-parallel
    - mtl
    - optparse-applicative
    - path
    - scientific
    - text
    - time
    - typed-process
    - yaml
executables:
  lhp:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-Wunused-packages'
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - lhp
tests:
  lhp-test:
    main: Spec.hs
    source-dirs: test/spec
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-Wunused-packages'
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies: []
  lhp-doctest:
    main: doctest.hs
    source-dirs: test/doctest
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-threaded'
    dependencies:
      - lhp
      - doctest
