name: hostpatrol
version: 0.0.16
github: vst/hostpatrol
license: MIT
author: Vehbi Sinan Tunalioglu
maintainer: vst@vsthost.com
copyright: Copyright (c) 2024 Vehbi Sinan Tunalioglu
extra-source-files:
  - README.md
  - CHANGELOG.md
description: Please see the README on GitHub at <https://github.com/vst/hostpatrol#readme>
dependencies:
  - base >= 4.7 && < 5
library:
  source-dirs: src
  ghc-options:
    - '-Wall'
    - '-Werror'
    - '-Wunused-packages'
  dependencies:
    - aeson
    - aeson-combinators
    - async-pool
    - autodocodec
    - autodocodec-schema
    - bytestring
    - file-embed
    - githash
    - mtl
    - optparse-applicative
    - path
    - scientific
    - string-interpolate
    - template-haskell
    - text
    - time
    - typed-process
    - yaml
executables:
  hostpatrol:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-Wunused-packages'
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies:
      - hostpatrol
tests:
  hostpatrol-test:
    main: Spec.hs
    source-dirs: test/spec
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-Wunused-packages'
      - '-threaded'
      - '-rtsopts'
      - '-with-rtsopts=-N'
    dependencies: []
  hostpatrol-doctest:
    main: doctest.hs
    source-dirs: test/doctest
    ghc-options:
      - '-Wall'
      - '-Werror'
      - '-threaded'
    dependencies:
      - hostpatrol
      - doctest
