import { HostPatrolReport, buildSshKeysTable } from '@/lib/data';
import dayjs from 'dayjs';
import LocalizedFormat from 'dayjs/plugin/localizedFormat';
import { FaCircleInfo } from 'react-icons/fa6';
import { SimpleBarChart, histogram } from '../helpers';
dayjs.extend(LocalizedFormat);

export function TabOverview({ data }: { data: HostPatrolReport }) {
  const sshkeys = Object.values(buildSshKeysTable(data));

  return (
    <div className="flex flex-col space-y-12">
      <div className="mt-4 grid grid-cols-4 gap-4">
        <div>
          <SimpleBarChart
            data={histogram((x) => (x.isKnown ? 'Known SSH Keys' : 'Unknown SSH Keys'), sshkeys, {
              'Known SSH Keys': 0,
              'Unknown SSH Keys': 0,
            })}
            size={[480, 320]}
          />
        </div>

        <div>
          <SimpleBarChart
            data={histogram((x) => x.timezone.split(' ', 1)[0] || 'UNKNOWN', data.hosts)}
            size={[480, 320]}
          />
        </div>

        <div>
          <SimpleBarChart data={histogram((x) => x.cloud.name, data.hosts)} size={[480, 320]} />
        </div>

        <div>
          <SimpleBarChart data={histogram((x) => x.distribution.name, data.hosts)} size={[480, 320]} />
        </div>
      </div>

      <div className="flex flex-col items-center">
        <div className="w-full max-w-4xl space-y-8 rounded border border-indigo-200 bg-indigo-100 p-6 shadow">
          <p className="text-center text-lg">
            {data.errors.length > 0 ? (
              <span className="text-red-600">
                <span className="font-bold">
                  {data.errors.length} error{data.errors.length === 1 ? '' : 's'}
                </span>{' '}
                were encountered during patrol.
              </span>
            ) : (
              <span className="text-green-600">No errors were encountered during the patrol.</span>
            )}
          </p>

          {data.errors.map((error, i) => (
            <div key={i} className="flex space-x-4 rounded border border-red-300 bg-red-200 p-4 text-red-600 shadow">
              <span className="font-bold ">{error.host}</span> <span className="font-light">{error.message}</span>
            </div>
          ))}

          <div className="text-center text-indigo-600">
            <FaCircleInfo className="inline" /> This report is generated by{' '}
            <abbr
              title={`${data.meta.buildTag} - ${data.meta.buildHash}`}
              className="cursor-help font-bold underline decoration-dashed"
            >
              hostpatrol v{data.meta.version}
            </abbr>{' '}
            on{' '}
            <abbr title={data.meta.timestamp} className="cursor-help font-bold underline decoration-dashed">
              {dayjs(data.meta.timestamp).format('LLLL')}
            </abbr>
            .
          </div>
        </div>
      </div>
    </div>
  );
}
