name: "Check Codebase"

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Codebase"
        uses: "actions/checkout@v5"

      - name: "Install Nix"
        uses: "DeterminateSystems/nix-installer-action@v20"

      - name: "Check, Test and Build Application"
        run: |
          nix develop --command bash -c "cabal update --ignore-project && cabal dev-test-build"

      - name: "Check, Test and Build Website"
        run: |
          nix develop --command bash -c "cd website && npm install && npm run check"
