name: "Check Codebase"

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Codebase"
        uses: "actions/checkout@v4"

      - name: "Install Nix"
        uses: "DeterminateSystems/nix-installer-action@v16"

      - name: "Use Nix Cache"
        uses: "DeterminateSystems/magic-nix-cache-action@v8"

      ## TODO: This should not be necessary, but nixpkgs v24.11 requires it.
      - name: "Update Haskell Package List"
        run: |
          nix-shell --pure --run "cabal update --ignore-project"

      - name: "Check Application"
        run: |
          nix-shell --pure --run "dev-test-build"

      - name: "Check Website"
        run: |
          nix-shell --pure --run "cd website && npm install && npm run check"
