name: "Check Codebase"

on:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout Codebase"
        uses: "actions/checkout@v4"

      - name: "Install nix"
        uses: "cachix/install-nix-action@v25"
        with:
          nix_path: "nixpkgs=channel:nixos-23.11"

      - name: "Use magic Nix cache"
        uses: "DeterminateSystems/magic-nix-cache-action@v3"

      - name: "Check"
        run: |
          nix-shell --run "dev-test-build"
