name: "Release"

on:
  push:
    branches:
      - "main"

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  release-please:
    runs-on: "ubuntu-latest"

    steps:
      - id: "release"
        name: "Release"
        uses: "googleapis/release-please-action@v4"

      - name: "Checkout Codebase"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 0

      - name: "Install Nix"
        uses: "DeterminateSystems/nix-installer-action@v16"

      - name: "Use Nix Cache"
        uses: "DeterminateSystems/magic-nix-cache-action@v8"

      ## TODO: This should not be necessary, but nixpkgs v24.11 requires it.
      - name: "Update Haskell Package List"
        run: |
          nix-shell --pure --run "cabal update --ignore-project"

      - name: "Build Application"
        if: "${{ steps.release.outputs.release_created }}"
        run: |
          nix-shell --run "bash build-static.sh"

      - name: "Upload Release Artifact"
        if: "${{ steps.release.outputs.release_created }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh release upload "${{ steps.release.outputs.tag_name }}" /tmp/hostpatrol-static-linux-x86_64
