name: "Release"

on:
  push:
    branches:
      - "main"

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  release-please:
    runs-on: "ubuntu-latest"

    steps:
      - id: "release"
        name: "Release"
        uses: "google-github-actions/release-please-action@v4"

      - name: "Checkout Codebase"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "actions/checkout@v4"

      - name: "Install nix"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "cachix/install-nix-action@v25"
        with:
          nix_path: "nixpkgs=channel:nixos-23.11"
          extra_nix_config: "system-features = benchmark, big-parallel, nixos-test, uid-range, kvm"

      - name: "Use magic Nix cache"
        if: "${{ steps.release.outputs.release_created }}"
        uses: "DeterminateSystems/magic-nix-cache-action@v3"

      - name: "Check Application"
        if: "${{ steps.release.outputs.release_created }}"
        run: |
          nix-shell --run "bash build-static.sh"

      - name: "Upload Release Artifact"
        if: "${{ steps.release.outputs.release_created }}"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
          gh release upload "${{ steps.release.outputs.tag_name }}" /tmp/lhp-static-linux-x86_64
